pipeline:
  name: test
  identifier: test
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: check
        identifier: check
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: CustomApproval
                  name: check
                  identifier: check
                  timeout: 20m
                  spec:
                    shell: Bash
                    retryInterval: 10s
                    scriptTimeout: 10m
                    source:
                      type: Inline
                      spec:
                        script: echo 'working'
                    environmentVariables: []
                    approvalCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: false
                        conditions:
                          - key: "1"
                            operator: equals
                            value: "1"
                    rejectionCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: false
                        conditions: []
                    onDelegate: true
                    outputVariables:
                      - name: var
                        type: String
                        value: pass
        tags: {}
