pipeline:
  name: test
  identifier: test
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: check
        identifier: check
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: CustomApproval
                  name: check
                  identifier: check
                  timeout: 20m
                  spec:
                    shell: Bash
                    retryInterval: 10s
                    scriptTimeout: 10m
                    source:
                      type: Inline
                      spec:
                        script: echo 'working'
                    environmentVariables: []
                    approvalCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: false
                        conditions:
                          - key: "1"
                            operator: equals
                            value: "1"
                    rejectionCriteria:
                      type: KeyValues
                      spec:
                        matchAnyCondition: false
                        conditions: []
                    onDelegate: true
                    outputVariables:
                      - name: var
                        type: String
                        value: pass
        tags: {}
    - stage:
        name: build-image
        identifier: buildimage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: ghcr.io/philip-walsh/
                    tags:
                      - testing
                    caching: true
  properties:
    ci:
      codebase:
        connectorRef: pwgh1
        repoName: recipe-api
        build: <+input>
