pipeline:
  name: publish-helmchart
  identifier: publishhelmchart
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: pwgh1
        repoName: recipe-api-helm
        build: <+input>
  stages:
    - stage:
        name: pub-helm
        identifier: pubhelm
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      set -e

                      helm version

                      echo "$DOCKER_PAT" | helm registry login registry-1.docker.io -u philipwalsh --password-stdin

                      rm -f *.tgz

                      helm package ./recipe-api

                      helm push recipe-api-$(grep 'version:' ./recipe-api/Chart.yaml | awk '{print $2}').tgz oci://registry-1.docker.io/philipwalsh
